### ISSUE TITLE
Oracle database choice

### ISSUE THREAD

**Issue by kaihendry** [aws-quickstart/quickstart-ibm-filenet-content-manager#10]
Noticed https://github.com/aws-quickstart/quickstart-ibm-filenet-content-manager/blob/master/templates/fncm-oracle.yaml

Is there no way to run this service using Postgres RDS instead?

**Comment by Vincent-Le** [comment]
> Noticed https://github.com/aws-quickstart/quickstart-ibm-filenet-content-manager/blob/master/templates/fncm-oracle.yaml
> 
> Is there no way to run this service using Postgres RDS instead?

@kaihendry - Unfortunately, not at the moment.

**Comment by antpas** [comment]
@kaihendry Has this changed since April 2020? I see in the [IBM documentation](https://www.ibm.com/support/knowledgecenter/SSNW2F_5.5.0/com.ibm.p8.containers.doc/containers_configuredb.htm) it supports PostgreSQL.

**Comment by Vincent-Le** [comment]
@antpas - IBM FileNet Content Manager itself supports PostgreSQL, but the FNCM Quickstart implementation only deploys  Oracle.  I'll defer to @abrakhan (current owner of this repo) to comment if there are any plans to update the FNCM Quickstart to allow PostgreSQL deployment.
