### ISSUE TITLE
Error when creating stack: Parameters: [AdditionalEKSAdminArns] do not exist in the template

### ISSUE THREAD

**Issue by mmwillingham** [aws-quickstart/quickstart-ibm-filenet-content-manager#12]
When attempting to create the stack, I'm getting the error
Parameters: [AdditionalEKSAdminArns] do not exist in the template

I have tried leaving blank (default) and specifying a valid value, but get the same error.

thanks
Martin

**Comment by abrakhan** [comment]
The error is because of a recent change in the EKS Quick Start.
The parameter - AdditionalEKSAdminArns - has been replaced with 2 parameters - AdditionalEKSAdminUserArn and AdditionalEKSAdminRoleArn
We are working on updating the FileNet P8 Quick Start template to reflect this change.

-Abrar

**Comment by mmwillingham** [comment]
Thanks Abrar
Do you have an ETA on the fix or a workaround in the meantime?

Martin

**Comment by vsnyc** [comment]
@mmwillingham - Thanks for raising this. I'm surprised that this passed our testing and merged to master, probably a timing issue. 

There are a couple of things we need to get this resolved:
1. The latest EKS quick start submodule no longer bundles the zip functions, rather they get packaged at test/build time using taskcat. So I need to upgrade our CI system to use v9 for testing this.

2. An unrelated but blocking change that we have to make is to use regional endpoints for Amazon S3 URLs referenced in the templates. See PR# https://github.com/aws-quickstart/quickstart-ibm-filenet-content-manager/pull/13. Once this is complete and has passed our testing, the EKS fix is relatively simple.

Subject to testing cycles, both changes should be addressed by Friday.

**Comment by mmwillingham** [comment]
Thanks for the update.

**Comment by mmwillingham** [comment]
Hello
Was the fix to this issue released today?

thanks
Martin

**Comment by vsnyc** [comment]
@mmwillingham Sorry for the late confirmation, but yes, we were able to resolve all the issues late Friday evening and push out an update. 

<img width="935" alt="IBM-FNCM-test-run" src="https://user-images.githubusercontent.com/624297/80399620-7f8b0080-8887-11ea-9e3f-6ec288c6f4d0.png">

Please test and let us know your findings. Make sure you disable rollback on the stack, so you can log back in and fetch any log files required for troubleshooting should you run into any errors.

One thing I observed in manual testing is that two of the SSM commands that initialize ICN and CPE containers timed out, but the environment seemed fully functional after a couple of hours or so. I'm checking with IBM how to address this better.

**Comment by vsnyc** [comment]
@mmwillingham - I had a discussion with @abrakhan on this. Although the CloudFormation stack was successful, because the SSM command timed out, the deployment was incomplete. 

This happened because the bastion host was not able to reach the CPE Ingress URL. I'm working on a fix for it. 

Meanwhile, as a workaround, in your initial deployment, please set `RemoteAccessCIDR` to `0.0.0.0/0`. This will ensure that the bastion host is able to access the public ALB URL for the CPE containers.

Once the deployment is complete you can go in and modify the security groups manually to restrict access to your IP range for the following security groups:
1. xxxx-BastionSecurityGroup-xxxx
2. xxxx-RemoteDesktopGatewaySG-xxxx

For the security groups created by ALB ingress controller, restrict access to your IP range, and the public IP of the bastion host.
1. xxxx-fncm-cpeingress-xxxx
2. xxxx-fncm-icningress-xxxx

I'll update the issue when a fix is added and then this workaround should no longer be necessary.

**Comment by mmwillingham** [comment]
The Quickstart stack completed with "CREATE_COMPLETE".
When I went into AWS Systems Manager > Commands, there were still a few commands running.
And after some time, three of them failed:
	1) Mount PVs and copy configuration files
		Failed step: downloadCorsFile
		----------ERROR-------
		fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
		failed to run commands: exit status 1
					
	2) Create Navigator Desktop and Repository
		Failed step: runICNScript
				
	3) Create GCD and Object Store
		Failed step: runOS1Script

- I logged into the bastion and can see the PV and PVCs all bound.
- The CPE and GraphQL pods are running and ready.
- The CSS and ICN pods are in ImagePullBackOff

- I logged into acce and I had to click "Finish"  to finish the domain creation.
- There is no Object Store and no Database Connection

**Comment by abrakhan** [comment]
@mmwillingham - Hi Martin,

We are looking into the domain creation issue. 
In the meantime, if you want to complete the deployment you need to run these 2 shell scripts on the Bastion host:

1. Object Store Creation
`cd /home/ec2-user`
`sudo ./FNCM_createOS1.sh cpe-ingress 80 <DomainAdminPassword>`
where DomainAdminPassword = the password you entered for the LDAP Admin account

2. Content Navigator Initialization
`cd /home/ec2-user`
`sudo ./FNCM_createDesktop.sh icn-ingress 80 <DomainAdminPassword> cpe-ingress 80`
where DomainAdminPassword = the password you entered for the LDAP Admin account

BTW, which region are you using for your deployment? Ohio?

Thanks.

-Abrar

**Comment by vsnyc** [comment]
@mmwillingham - Thanks for the continued investigation and great catch.

> 1) Mount PVs and copy configuration files
> Failed step: downloadCorsFile
> ----------ERROR-------
> fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
> failed to run commands: exit status 1

Looks like this is due to a typo in the [fncm-crs-deploy.yaml][1] template. The extension should have been a lowercase `FNCM_cors.template`. I'll push a fix.

[1]: https://github.com/aws-quickstart/quickstart-ibm-filenet-content-manager/blob/953fca40f5f7a459bd99e2438bd4cf903549d743/templates/fncm-crs-deploy.yaml#L164-L169

**Comment by mmwillingham** [comment]
Hi Abrar and vnyc,
I ran the object store creation script and it ran successfully and I can see OS1 in ACCE.

The ICN script failed..it just repeats the line "Navigator pods have not started yet, wait 30 seconds and retry again...."
I think because it can't create the pods. 
$ kubectl get pods
NAME                        READY   STATUS             RESTARTS   AGE
fncm-cpe-6c58f59d44-9b6c5   1/1     Running            0          29m
fncm-cpe-6c58f59d44-jdtj8   1/1     Running            0          30m
fncm-cpe-6c58f59d44-vk78v   1/1     Running            0          30m
fncm-crs-67df6c48b5-ftvm5   1/1     Running            0          19h
fncm-crs-67df6c48b5-lrmnp   1/1     Running            0          19h
fncm-css-5c465fd99-54m6p    0/1     ImagePullBackOff   0          19h
fncm-icn-54c4b8db5d-nts6b   0/1     ImagePullBackOff   0          21m
fncm-icn-54c4b8db5d-tt8x9   0/1     ImagePullBackOff   0          21m
fncm-icn-54c4b8db5d-z25sd   0/1     ImagePullBackOff   0          21m

Notice, it also fails trying to create CSS. And I don't see any CSS components in the object store.

CSS
kubectl describe pod fncm-css-5c465fd99-54m6p 
  Normal   BackOff  104s (x5066 over 19h)  kubelet, ip-10-0-49-173.us-east-2.compute.internal  Back-off pulling image "937870415058.dkr.ecr.us-east-2.amazonaws.com/ibm-f-cssre-12i71x184yuzs:ga-554-p8css-if001"

ICN (more helpful info)
kubectl describe pod fncm-icn-54c4b8db5d-z25sd
Failed to pull image "937870415058.dkr.ecr.us-east-2.amazonaws.com/ibm-f-icnre-1hhp40e7oxuti:ga-307-icn-if002": rpc error: code = Unknown desc = Error response from daemon: manifest for 937870415058.dkr.ecr.us-east-2.amazonaws.com/ibm-f-icnre-1hhp40e7oxuti:ga-307-icn-if002 not found
Error: ErrImagePull
Pulling image "937870415058.dkr.ecr.us-east-2.amazonaws.com/ibm-f-icnre-1hhp40e7oxuti:ga-307-icn-if002"
Error: ImagePullBackOff
Back-off pulling image "937870415058.dkr.ecr.us-east-2.amazonaws.com/ibm-f-icnre-1hhp40e7oxuti:ga-307-icn-if002

Thanks!
Martin

**Comment by abrakhan** [comment]
@mmwillingham 

Can you make sure the ECR repositories were created and have the images in them?
E.g.,
![aws-ecr-repos](https://user-images.githubusercontent.com/34386592/80636036-a412e400-8a11-11ea-8dbd-752fcefc02ab.jpg)
![aws-ecr-repos-images](https://user-images.githubusercontent.com/34386592/80636264-05d34e00-8a12-11ea-8505-0598f57b72f9.jpg)

-Abrar

**Comment by mmwillingham** [comment]
Hi Abrar,
I have the 5 repositories, but only some have images
****repository (name shortened)       Image tag**
- cmisr                                        ga-304-cmis-if010
- cpere                                        ga-554-p8cpe-if001
- crsre                                         ga-554-p8cgql-if001
- cssre                                        NONE
- icnre                                        NONE

Thanks
Martin

**Comment by abrakhan** [comment]
Looks like either you don't have access to the CSS and ICN containers in the IBM Registry or there was an error downloading them to ECR.

You can check the download status of the FNCM containers download here:
![aws-ecr-repos-ssm](https://user-images.githubusercontent.com/34386592/80640337-1b4b7680-8a18-11ea-8a99-b594728b8b2d.jpg)

-Abrar

**Comment by mmwillingham** [comment]
thanks
In the AWS Systems Manager, here are the results for the "Pulling docker images, tagging images, and pushing to AWS ECR" step:

- PullCSSContainer    Error response from daemon: pull access denied for cp.icr.io/cp/cp4a/fncm/css, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

- PullICNContainer     Error response from daemon: pull access denied for cp.icr.io/cp/cp4a/ban/navigator, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

- PullCPEContainer     Status: Downloaded newer image for cp.icr.io/cp/cp4a/fncm/cpe:ga-554-p8cpe-if
- PullCMISContainer   Status: Downloaded newer image for cp.icr.io/cp/cp4a/fncm/cmis:ga-304-cmis-if010
- PullCQLContainer  Status: Downloaded newer image for cp.icr.io/cp/cp4a/fncm/graphql:ga-554-p8cgql-if001

I believe I should have access to the repositories because I have recently downloaded the images in an OpenShift implementation. For the CSS example, here is the image pull target for my OpenShift yaml file, which matches what the QuickStart is trying to pull and tag.
     css:
       arch:
         amd64: "3 - Most preferred"
       replica_count: 1
       image:
         repository: cp.icr.io/cp/cp4a/fncm/css
         tag: ga-554-p8css-if001

**Comment by abrakhan** [comment]
Can you try to download the CSS and ICN images on the Bastion host?

Here are the commands:

Login to the IBM Entitlement Registry:
`sudo docker login -u cp -p <Entitlement_Key> cp.icr.io`

Download the CSS container image
`sudo docker pull cp.icr.io/cp/cp4a/fncm/css:ga-554-p8css-if001`

Download the Content Navigator container image
`sudo docker pull cp.icr.io/cp/cp4a/ban/navigator:ga-307-icn-if002`

-Abrar

**Comment by mmwillingham** [comment]
Hi Abrar,
Those commands were successful.
$ sudo docker login -u cp -p <redacted> cp.icr.io
Login Succeeded
$ sudo docker pull cp.icr.io/cp/cp4a/fncm/css:ga-554-p8css-if001
$ sudo docker pull cp.icr.io/cp/cp4a/ban/navigator:ga-307-icn-if002

$ sudo docker images
REPOSITORY                                                               TAG                  
cp.icr.io/cp/cp4a/fncm/css                                               ga-554-p8css-if001   
937870415058.dkr.ecr.us-east-2.amazonaws.com/ibm-f-cmisr-1odf0q65rxyvn   ga-304-cmis-if010    
cp.icr.io/cp/cp4a/fncm/cmis                                              ga-304-cmis-if010    
cp.icr.io/cp/cp4a/fncm/graphql                                           ga-554-p8cgql-if001  
937870415058.dkr.ecr.us-east-2.amazonaws.com/ibm-f-crsre-1cwooswwxvcsk   ga-554-p8cgql-if001  
937870415058.dkr.ecr.us-east-2.amazonaws.com/ibm-f-cpere-m1hnyt0udez0    ga-554-p8cpe-if001   
cp.icr.io/cp/cp4a/fncm/cpe                                               ga-554-p8cpe-if001   
cp.icr.io/cp/cp4a/ban/navigator                                          ga-307-icn-if002

**Comment by abrakhan** [comment]
That's odd. These are the exact same commands used in the Cloudformation template. 
Since you have the container images downloaded on Bastion host - you can use the push commands to tag them and push them to the ECR. The instructions to do this are available under:

_ECR > Repositories > {select a repository} > View push commands_

**Note:** You can skip step 2 - Build your docker image

-Abrar

**Comment by mmwillingham** [comment]
When I ran the push command for CSS I got an error:
$ aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 937870415058.dkr.ecr.us-east-2.amazonaws.com/ibm-f-cssre-12i71x184yuzs
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/auth: dial unix /var/run/docker.sock: connect: permission denied

**Comment by mmwillingham** [comment]
HI Abrar,
Any suggestions on how to get past the login issue?

thanks

**Comment by abrakhan** [comment]
@mmwillingham - Hi Martin - It may be best to get on a remote session (e.g. WebEx) and troubleshoot your environment. Email me your availability and I will send you a meeting invite. 
My email id is: abrarkhan@hotmail.com.

Thanks.

-Abrar

**Comment by vsnyc** [comment]
> HI Abrar,
> Any suggestions on how to get past the login issue?
> 
> thanks

Hi Martin, this appears to be related to the permissions when executing docker commands. I've checked that sudo works. See the commands below, the first one reproduces the error and second one succeeds.

```
[ec2-user@ip-10-0-152-46 ~]$ aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 91xxxxxxxxx96.dkr.ecr.us-east-2.amazonaws.com/ibm-f-cssre-1gglejfx0t2li
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/auth: dial unix /var/run/docker.sock: connect: permission denied

[ec2-user@ip-10-0-152-46 ~]$ aws ecr get-login-password --region us-east-2 | sudo docker login --username AWS --password-stdin 91xxxxxxxxx96.dkr.ecr.us-east-2.amazonaws.com/ibm-f-cssre-1gglejfx0t2li
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

**Comment by mmwillingham** [comment]
Thanks Vinod

I was able to run the command, but then I couldn't run the tag command:
$ aws ecr get-login-password --region us-east-2 | sudo docker login
--username AWS --password-stdin
937870415058.dkr.ecr.us-east-2.amazonaws.com/ibm-f-cssre-12i71x184yuzs
WARNING! Your password will be stored unencrypted in
/root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

$ docker tag ibm-f-cssre-12i71x184yuzs:latest
937870415058.dkr.ecr.us-east-2.amazonaws.com/ibm-f-cssre-12i71x184yuzs:latest
Got permission denied while trying to connect to the Docker daemon socket
at unix:///var/run/docker.sock: Post http://
%2Fvar%2Frun%2Fdocker.sock/v1.40/images/ibm-f-cssre-12i71x184yuzs:latest/tag?repo=
937870415058.dkr.ecr.us-east-2.amazonaws.com%2Fibm-f-cssre-12i71x184yuzs&tag=latest:
dial unix /var/run/docker.sock: connect: permission denied


Martin

**Comment by vsnyc** [comment]
Hi Martin, looks like it will work with elevated privileges, i.e. `sudo docker ...`. Please try and let us know. Feel free to reach out to me on LinkedIn from my profile if you'd like to arrange a meeting.

**Comment by mmwillingham** [comment]
Hi Vinod,
When I try to tag, it says it doesn't exist.

$ sudo docker pull cp.icr.io/cp/cp4a/fncm/css:ga-554-p8css-if001
ga-554-p8css-if001: Pulling from cp/cp4a/fncm/css
Digest:
sha256:c6b5e87e4149f4a2e31552e53b0417258fd098d23c801bf8903bb3be302bc5ee
Status: Image is up to date for
cp.icr.io/cp/cp4a/fncm/css:ga-554-p8css-if001
cp.icr.io/cp/cp4a/fncm/css:ga-554-p8css-if001

*Commands from ECR repository push commands*
$ aws ecr get-login-password --region us-east-2 | sudo docker login
--username AWS --password-stdin
937870415058.dkr.ecr.us-east-2.amazonaws.com/ibm-f-cssre-12i71x184yuzs
WARNING! Your password will be stored unencrypted in
/root/.docker/config.json.

$ sudo docker tag ibm-f-cssre-12i71x184yuzs:latest
937870415058.dkr.ecr.us-east-2.amazonaws.com/ibm-f-cssre-12i71x184yuzs:latest
Error response from daemon: No such image: ibm-f-cssre-12i71x184yuzs:latest

thanks

**Comment by mmwillingham** [comment]
HI Vinod and Abrar,
I'm available for a remote session at these times.
But before that, I'm going to delete the stack and re-create.

- today after 3:30pm Eastern Time
- tomorrow (Wed) from 9am - 11:30am and 12:30pm - 3pm
- Thurs 9am - 12pm
- Fri  9am - 6pm

**Comment by mmwillingham** [comment]
Hi guys,
I deleted the existing stack and re-created a new one from scratch and
everything created with no errors.
I'm able to login to ACCE and ICN. The CSS indexes were all created.

The only issue I see now is that there is a certificate error when logging
in with https. I specified my AWS certificate during the quick start
parameters. Is there something else I need to do?

Thanks!
Martin

**Comment by mmwillingham** [comment]
Thanks very much to both of you.
After deleting and recreating the stack, everything worked perfectly. Once the stack completion was complete, I didn't have to do anything extra. I was able to login to ACCE and ICN and could see the CSS indexes.

**Comment by vsnyc** [comment]
Thanks Martin, that's great to hear. Appreciate the feedback and your patience as we worked through.
