### ISSUE TITLE
IBM Content Navigator - Registering custom plugins

### ISSUE THREAD

**Issue by abrakhan** [aws-quickstart/quickstart-ibm-filenet-content-manager#14]
These are steps to register custom plugins in IBM Content Navigator after you have completed the deployment of FileNet Content Manager on AWS.

1. Transfer Plugin file to Bastion host
      Use the _/home/ec-user_ directory for easy reference

2. Copy plugin (.jar) file to the shared Navigator volume map
      `sudo su -`
      `cd /data/ecm/icn/pluginstore`
      `cp /home/ec-user/<plugin>.jar .`
      `chown 50001:root <plugin>.jar`
       `ls -l   `     (verify the file ownership and size)
       `exit`

3. **[Optional]** Verify the plugin file is available inside the Navigator pods
      `kubectl get pods | grep icn`
      `kubectl exec -it <pod_name> bash`        (use any podname from the previous command)
      `cd /opt/ibm/plugins`
      `ls -l   `    (verify the file ownership and size)
      `exit`

4. Load plugin in Navigator Administration Desktop
      Use this path in the Jar file path parameter value field
      `/opt/ibm/plugins/<plugin>.jar`

**Comment by vsnyc** [comment]
Thanks Abrar, this is helpful.
